routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
 */

Route::get('/', function () {
	return view('welcome');
})->name('home');

// Social Login Routes
Route::get('login/{provider}', [HomeController::class, 'socialLogin'])->name('social-login');
Route::get('login/{provider}/callback', [HomeController::class, 'socialLoginCallback']);
// Social Login Routes

Route::middleware(['auth', 'verified'])->group(function () {
	Route::get('/dashboard', [HomeController::class, 'user_dashboard'])->name('dashboard');
	Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
	Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
	Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

	Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['role:admin']], function () {
		Route::get('/', [HomeController::class, 'index'])->name('dashboard');
		Route::resource('roles', RoleController::class, ['names' => 'role']);
	});
});
require __DIR__.'/auth.php';

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class RoleController extends Controller {
	/**
	 * Display a listing of the resource.
	 */
	public function index(Request $request) {
		if ($request->ajax()) {
			return Datatables::of(Role::whereNot('name','admin')->get())
				->addIndexColumn()
				->addColumn('checkbox', function ($row) {
					return "<div class='form-check form-check-sm form-check-custom form-check-solid'>
								<input class='form-check-input' type='checkbox' value='".$row->id."' />
							</div>";
				})
				->addColumn('action', function ($row) {
					$action = '<div class="d-flex justify-content-center flex-shrink-0">';
					$action .= '<a href="'.route('admin.role.edit', ['role' => $row->id]).'" target-header="Edit role" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1" title="Edit">
						<span class="svg-icon svg-icon-3">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
								<path opacity="0.3" d="M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.0825 1.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.9962 6.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.06399 20.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.7934 2.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z" fill="#009ef7"></path>
								<path d="M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.3789 21.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.696 18.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z" fill="#009ef7"></path>
							</svg>
						</span>
					</a>';

					$action .= '<a target-url="'.route('admin.role.destroy', ['role' => $row->id]).'" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm delete-role" data-kt-modules-table-filter="delete_row" title="Delete">
						<span class="svg-icon svg-icon-3">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
								<path d="M5 9C5 8.44772 5.44772 8 6 8H18C18.5523 8 19 8.44772 19 9V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V9Z" fill="#009ef7"></path>
								<path opacity="0.5" d="M5 5C5 4.44772 5.44772 4 6 4H18C18.5523 4 19 4.44772 19 5V5C19 5.55228 18.5523 6 18 6H6C5.44772 6 5 5.55228 5 5V5Z" fill="#009ef7"></path>
								<path opacity="0.5" d="M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4V4H9V4Z" fill="#009ef7"></path>
							</svg>
						</span>
					</a>';

					return $action .= '</div>';
				})
				->rawColumns(['action', 'checkbox', 'image'])
				->make(true);
		}

		return view('admin.roles.index');
	}

	/**
	 * Show the form for creating a new resource.
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 */
	public function store(Request $request) {
		
	}

	/**
	 * Display the specified resource.
	 */
	public function show(Role $role) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 */
	public function edit(Role $role) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 */
	public function update(Request $request, Role $role) {
		//
	}

	/**
	 * Remove the specified resource from storage.
	 */
	public function destroy(Role $role) {
		//
	}
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app')

@section('title', isset($category) ? 'Edit Category' : 'Add Category')

@section('css')
@endsection

@section('content')
	<!--begin::Toolbar-->
	<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
		<!--begin::Toolbar container-->
		<div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
			<!--begin::Page title-->
			<div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
				<!--begin::Breadcrumb-->
				<ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
					<!--begin::Item-->
					<li class="breadcrumb-item text-primary">
						<a href="{{ route('admin.dashboard') }}" class="text-primary text-hover-primary">Dashboard</a>
					</li>
					<!--end::Item-->
					<!--begin::Item-->
					<li class="breadcrumb-item">
						<span class="bullet bg-gray-400 w-5px h-2px"></span>
					</li>
					<!--end::Item-->
					<!--begin::Item-->
					<li class="breadcrumb-item text-primary">
						<a href="{{ route('admin.category.index') }}" class="text-primary text-hover-primary">Categories</a>
					</li>
					<!--end::Item-->
					<!--begin::Item-->
					<li class="breadcrumb-item">
						<span class="bullet bg-gray-400 w-5px h-2px"></span>
					</li>
					<!--end::Item-->
					<!--begin::Item-->
					<li class="breadcrumb-item text-muted">{{ isset($category) ? 'Edit ' : 'Create ' }}</li>
					<!--end::Item-->
				</ul>
				<!--end::Breadcrumb-->
			</div>
			<!--end::Page title-->
		</div>
		<!--end::Toolbar container-->
	</div>
	<!--end::Toolbar-->

	<!--begin::Content-->
	<div id="kt_app_content" class="app-content flex-column-fluid">
		<!--begin::Content container-->
		<div id="kt_app_content_container" class="app-container container-xxl">
			<div class="row">
				<div class="col-md-8 offset-md-2">
					<!--begin::Card-->
					<div class="card">
						<!--begin::Card header-->
						<div class="card-header" id="kt_chat_contacts_header">
							<!--begin::Card title-->
							<div class="card-title">
								<h2>{{ isset($category) ? 'Edit ' : 'Add ' }} Category</h2>
							</div>
							<!--end::Card title-->
						</div>
						<!--end::Card header-->
						<!--begin::Card body-->
						<div class="card-body py-4">
							<!--begin::Form-->
							<form id="category_form" class="form" novalidate="novalidate" method="POST"
								action="{{ isset($category) ? route('admin.category.update', $category) : route('admin.category.store') }}"
								enctype="multipart/form-data">
								@csrf
								@isset($category)
									<input type="hidden" name="_method" value="put" />
								@endisset
								<div class="row row-cols-1 row-cols-sm-2 rol-cols-md-1 row-cols-lg-2">
									<!--begin::Col-->
									<div class="col">
										<!--begin::Input group-->
										<div class="fv-row mb-7 fv-plugins-icon-container">
											<!--begin::Label-->
											<label class="required fs-6 fw-semibold form-label mt-3">Name</label>
											<!--end::Label-->
											<!--begin::Input-->
											<input type="name" class="form-control form-control-solid @error('name') is-invalid @enderror"
												name="name" value="{{ old('name', @$category->name) }}" placeholder="Name">
											<!--end::Input-->
											@error('name')
												<div id="name-error" class="invalid-feedback">{{ $message }}</div>
											@enderror
											<div class="fv-plugins-message-container invalid-feedback"></div>
										</div>
										<!--end::Input group-->
									</div>
									<!--end::Col-->
									<!--begin::Col-->
									<div class="col">
										<!--begin::Input group-->
										<div class="fv-row mb-7">
											<!--begin::Label-->
											<label class="fs-6 fw-semibold form-label mt-3">
												Parent Category
											</label>
											<!--end::Label-->
											<!--begin::Input-->
											<div class="input-group input-group-solid flex-nowrap">
												<span class="input-group-text"><i class="bi bi-calendar fs-4"></i></span>
												<div class="overflow-hidden flex-grow-1">
													<select class="form-select form-select-solid rounded-start-0 border-start" data-control="select2"
														data-placeholder="Select an option" name="parent_category_id">
														<option></option>
														@forelse ($categories as $parent_category)
															<option value="{{ $parent_category->id }}"
																{{ old('parent_category_id', @$category->parent_category_id) == $parent_category->id ? 'selected' : '' }}>
																{{ ucwords($parent_category->name) }}</option>
														@empty
														@endforelse
													</select>
												</div>
											</div>
											<!--end::Input-->
										</div>
										<!--end::Input group-->
									</div>
									<!--end::Col-->
								</div>
								<div class="row">
									<!--begin::Col-->
									<div class="col-md-12">
										<div class="row mb-6">
											<!--begin::Label-->
											<label class="col-md-3 col-form-label fw-bold fs-6">Category logo</label>
											<!--end::Label-->
											<!--begin::Col-->
											<div class="col-md-9">
												<!--begin::Image input-->
												<div class="image-input image-input-outline" data-kt-image-input="true"
													style="background-image: url({{ asset('assets/media/default.jpg') }})">
													<!--begin::Preview existing avatar-->
													<div class="image-input-wrapper w-125px h-125px"
														style="background-image: url( {{ @$category->full_image_url ?? asset('assets/media/default.jpg') }} );">
													</div>
													<!--end::Preview existing avatar-->
													<!--begin::Label-->
													<label class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow"
														data-kt-image-input-action="change" data-bs-toggle="tooltip" title="Change">
														<i class="bi bi-pencil-fill fs-7"></i>
														<!--begin::Inputs-->
														<input type="file" name="image" accept="image/*" />
														<!--end::Inputs-->
													</label>
													<!--end::Label-->
													<!--begin::Cancel-->
													<span class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow"
														data-kt-image-input-action="cancel" data-bs-toggle="tooltip" title="Cancel">
														<i class="bi bi-x fs-2"></i>
													</span>
													<!--end::Cancel-->
													<!--begin::Remove-->
													<span class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow"
														data-kt-image-input-action="remove" data-bs-toggle="tooltip" title="Remove">
														<i class="bi bi-x fs-2"></i>
													</span>
													<!--end::Remove-->
												</div>
												<!--end::Image input-->
												<!--begin::Hint-->
												<div class="form-text">Allowed file types: Images/*.</div>
												<!--end::Hint-->
											</div>
											<!--end::Col-->
										</div>
									</div>
									<!--end::Col-->
								</div>
								<!--begin::Actions-->
								<div class="text-center">
									<button type="submit" class="btn btn-primary submit-btn" data-kt-services-modal-action="submit">
										<span class="indicator-label">Submit</span>
										<span class="indicator-progress">Please wait...
											<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
									</button>
									<a href="javascript:history.back()" class="btn btn-danger me-3">Back</a>
								</div>
								<!--end::Actions-->
							</form>
							<!--end::Form-->
						</div>
						<!--end::Card body-->
					</div>
					<!--end::Card-->
				</div>
			</div>
		</div>
		<!--end::Content container-->
	</div>
	<!--end::Content-->
@endsection

@section('js')
	@if (isset($category))
		{!! JsValidator::formRequest('App\Http\Requests\Category\UpdateCategoryRequest', '#category_form') !!}
	@else
		{!! JsValidator::formRequest('App\Http\Requests\Category\StoreCategoryRequest', '#category_form') !!}
	@endif

	<script type="text/javascript">
		var categoryListUrl = "{{ route('admin.category.index') }}";
	</script>
	<script src="{{ asset('assets/js/admin/category.js') }}"></script>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Roles')

@section('css')
@endsection

@section('content')
	<!--begin::Toolbar-->
	<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
		<!--begin::Toolbar container-->
		<div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
			<!--begin::Page title-->
			<div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
				<!--begin::Breadcrumb-->
				<ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
					<!--begin::Item-->
					<li class="breadcrumb-item text-primary">
						<a href="{{ route('admin.dashboard') }}" class="text-primary text-hover-primary">Dashboard</a>
					</li>
					<!--end::Item-->
					<!--begin::Item-->
					<li class="breadcrumb-item">
						<span class="bullet bg-gray-400 w-5px h-2px"></span>
					</li>
					<!--end::Item-->
					<!--begin::Item-->
					<li class="breadcrumb-item text-muted">Roles</li>
					<!--end::Item-->
				</ul>
				<!--end::Breadcrumb-->
			</div>
			<!--end::Page title-->
		</div>
		<!--end::Toolbar container-->
	</div>
	<!--end::Toolbar-->

	<!--begin::Content-->
	<div id="kt_app_content" class="app-content flex-column-fluid">
		<!--begin::Content container-->
		<div id="kt_app_content_container" class="app-container container-xxl">
			<!--begin::Card-->
			<div class="card">
				<!--begin::Card header-->
				<div class="card-header border-0 pt-6">
					<!--begin::Card title-->
					<div class="card-title">
						<!--begin::Search-->
						<div class="d-flex align-items-center position-relative my-1">
							<!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
							<span class="svg-icon svg-icon-1 position-absolute ms-6">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1"
										transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
									<path
										d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z"
										fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
							<input type="text" data-kt-role-table-filter="search" class="form-control form-control-solid w-250px ps-14"
								placeholder="Search role" />
						</div>
						<!--end::Search-->
					</div>
					<!--begin::Card title-->
					<!--begin::Card toolbar-->
					<div class="card-toolbar">
						<!--begin::Toolbar-->
						<div class="d-flex justify-content-end" data-kt-role-table-toolbar="base">
							<!--begin::Add role-->
							<a href="{{ route('admin.role.create') }}" class="btn btn-light-primary">
								<!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
								<span class="svg-icon svg-icon-3">
									<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
										<rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5"
											fill="currentColor"></rect>
										<rect x="10.8891" y="17.8033" width="12" height="2" rx="1"
											transform="rotate(-90 10.8891 17.8033)" fill="currentColor"></rect>
										<rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="currentColor"></rect>
									</svg>
								</span>
								<!--end::Svg Icon-->Add Role
							</a>
							<!--end::Add role-->
						</div>
						<!--end::Toolbar-->

						<!--begin::Group actions-->
						<div class="d-flex justify-content-end align-items-center d-none delete-all-button-div ms-3 ms-3"
							data-kt-module-table-toolbar="selected">
							<div class="fw-bolder me-5">
								<span class="me-2" data-kt-module-table-select="selected_count"></span>Selected
							</div>
							<button type="button" class="btn btn-danger" data-kt-module-table-select="delete_selected"
								target-url="{{ route('admin.role.destroy', ['role' => 0]) }}">Delete Selected</button>
						</div>
						<!--end::Group actions-->
					</div>
					<!--end::Card toolbar-->
				</div>
				<!--end::Card header-->
				<!--begin::Card body-->
				<div class="card-body py-4">
					<!--begin::Table-->
					<table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_table_roles">
						<!--begin::Table head-->
						<thead>
							<!--begin::Table row-->
							<tr class="text-start text-muted fw-bold fs-7 text-uppercase gs-0">
								<th class="w-10px px-2">
									<div class="form-check form-check-sm form-check-custom form-check-solid me-3">
										<input class="form-check-input" type="checkbox" data-kt-check="true"
											data-kt-check-target="#kt_table_roles form-check-input" value="1" />
									</div>
								</th>
								<th class="min-w-150px">Role</th>
								<th>Create Date</th>
								<th class="text-center min-w-100px">Actions</th>
							</tr>
							<!--end::Table row-->
						</thead>
						<!--end::Table head-->
						<!--begin::Table body-->
						<tbody class="text-gray-600 fw-semibold"></tbody>
						<!--end::Table body-->
					</table>
					<!--end::Table-->
				</div>
				<!--end::Card body-->
			</div>
			<!--end::Card-->
		</div>
		<!--end::Content container-->
	</div>
	<!--end::Content-->
@endsection

@section('js')
	<script type="text/javascript">
		var roleListUrl = "{{ route('admin.role.index') }}";
	</script>
	<script src="{{ asset('assets/js/admin/role.js') }}"></script>
@endsection